name = "spin-mama-casino-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-mama-casino.de"
HMAC_KEY = "1adf3e9145321d29aa2bb291e275b3b32a07ed23cfc9fd2ccdd781b0baebfe9e"
COOKIE_NAME = "oj8"
PLAY_PATH = "try"
BUTTON_ID = "p64d316c283fa07d7d14dd43dbb0c0dc5"
GATE_SALT = "c327adfd88e0b866"
